basePath: /
info:
  contact:
    email: Jacques.KOZIK@etu.uca.fr ou Marc_Achraf_Atef.MORCOS@etu.uca.fr
    name: Jacques KOZIK et Marc MORCOS.
  description: API to manage Scheduler.
  title: middleware/ Scheduler API
  version: 1.0.0
paths: {}
schemes:
- http
swagger: "2.0"
